<?php
/**
 * Slate Ops — Supervisor Dashboard data layer.
 *
 * Phase 1: server-rendered stub data derived from the Claude design reference.
 * Real operational wiring can replace the entire payload through:
 *   apply_filters( 'slate_ops_supervisor_refresh', $payload )
 */
if (!defined('ABSPATH')) exit;

class Slate_Ops_Supervisor_Dashboard {

  public static function get_tabs() {
    return [
      ['id' => 'overview', 'label' => 'Overview'],
      ['id' => 'blocked', 'label' => 'Blocked Jobs', 'count_key' => 'blocked'],
      ['id' => 'schedule', 'label' => 'Schedule'],
      ['id' => 'techs', 'label' => 'Techs'],
      ['id' => 'qc', 'label' => 'QC / Rework', 'count_key' => 'qc'],
      ['id' => 'ready', 'label' => 'Ready Queue', 'count_key' => 'ready'],
    ];
  }

  public static function get_blocked_categories() {
    return [
      'Parts',
      'Scope / Engineering',
      'Customer / Dealer',
      'QC Issue',
      'Tooling / Bay',
      'Tech Needs Help',
      'Admin / Paperwork',
    ];
  }

  public static function get_jobs() {
    return [
      [
        'id' => 'S-ORD101392',
        'so' => 'SO-44218',
        'customer' => 'Sigma Logistics',
        'dealer' => 'MBWIL',
        'tech' => ['name' => 'Marco Reyes', 'initials' => 'MR'],
        'status' => 'blocked',
        'status_label' => 'Blocked',
        'step' => 'Electrical rough-in',
        'due' => 'May 14',
        'due_delta' => -1,
        'issue' => 'Awaiting wiring harness — vendor revised ETA',
        'issue_short' => 'Parts hold',
        'blocked_category' => 'Parts',
        'blocked_reason' => 'Wiring harness PN 44-218B back-ordered. Vendor revised ETA to 5/16.',
        'time_blocked' => '2d 4h',
        'last_note' => 'Vendor confirmed 5/16 ship — Logan, 1h ago',
        'action' => 'Review blocker',
        'parts' => 'Partial — 6 of 8 lines',
        'parts_risk' => 'high',
        'qc' => 'Not started',
        'bay' => 'Bay 4',
        'work_center' => 'Electrical',
        'priority' => 'high',
        'notes' => [
          ['who' => 'Logan T.', 'role' => 'Parts', 'when' => '1h ago', 'text' => 'Vendor confirmed 5/16 ship. PO updated.'],
          ['who' => 'Marco R.', 'role' => 'Tech', 'when' => 'Yesterday 4:12p', 'text' => 'Harness short — cannot continue trim. Moving to next available task.'],
          ['who' => 'Supervisor', 'role' => 'Sup', 'when' => 'Yesterday 9:08a', 'text' => 'Hold posted. Helper not required.'],
        ],
      ],
      [
        'id' => 'S-ORD101393',
        'so' => 'SO-44219',
        'customer' => 'Sigma Logistics',
        'dealer' => 'MBWIL',
        'tech' => ['name' => 'Devin Park', 'initials' => 'DP'],
        'status' => 'in-progress',
        'status_label' => 'In Progress',
        'step' => 'Floor & wall install',
        'due' => 'May 15',
        'due_delta' => 0,
        'issue' => 'On track — confirm parts ETA for ladder rack',
        'issue_short' => 'Confirm parts ETA',
        'blocked_category' => null,
        'blocked_reason' => null,
        'time_blocked' => null,
        'last_note' => 'Floor primer complete — Devin, 22m ago',
        'action' => 'Confirm ETA',
        'parts' => 'Complete',
        'parts_risk' => 'low',
        'qc' => 'Pending stage 2',
        'bay' => 'Bay 2',
        'work_center' => 'Interior',
        'priority' => 'med',
        'notes' => [],
      ],
      [
        'id' => 'S-ORD101394',
        'so' => 'SO-44220',
        'customer' => 'Sigma Logistics',
        'dealer' => 'MBWIL',
        'tech' => ['name' => 'Jules Okafor', 'initials' => 'JO'],
        'status' => 'in-progress',
        'status_label' => 'In Progress',
        'step' => 'Cabinetry install',
        'due' => 'May 16',
        'due_delta' => 1,
        'issue' => 'Decision needed: customer-supplied shelving variant',
        'issue_short' => 'Decision needed',
        'blocked_category' => null,
        'blocked_reason' => null,
        'time_blocked' => null,
        'last_note' => 'Cabinet template fit-checked — Jules, 1h ago',
        'action' => 'Resolve parts hold',
        'parts' => 'Partial — 12 of 14 lines',
        'parts_risk' => 'med',
        'qc' => 'Not started',
        'bay' => 'Bay 1',
        'work_center' => 'Cabinetry',
        'priority' => 'med',
        'notes' => [],
      ],
      [
        'id' => 'S-ORD101350',
        'so' => 'SO-44181',
        'customer' => 'Mercedes-Benz of Wilsonville',
        'dealer' => 'MBWIL',
        'tech' => ['name' => 'Antonia Ruiz', 'initials' => 'AR'],
        'status' => 'complete',
        'status_label' => 'Complete — Awaiting Pickup',
        'step' => 'Closeout',
        'due' => 'May 13',
        'due_delta' => 0,
        'issue' => 'Ready for pickup notification',
        'issue_short' => 'Notify customer',
        'blocked_category' => null,
        'blocked_reason' => null,
        'time_blocked' => null,
        'last_note' => 'Closeout photos uploaded — Antonia, 3h ago',
        'action' => 'Notify customer',
        'parts' => 'Complete',
        'parts_risk' => 'low',
        'qc' => 'Signed off',
        'bay' => 'Bay 6',
        'work_center' => 'Closeout',
        'priority' => 'low',
        'notes' => [],
      ],
      [
        'id' => 'S-ORD101401',
        'so' => 'SO-44226',
        'customer' => 'Pacific Plumbing Co.',
        'dealer' => '—',
        'tech' => ['name' => 'Sam Hadley', 'initials' => 'SH'],
        'status' => 'blocked',
        'status_label' => 'Blocked',
        'step' => 'Scope review',
        'due' => 'May 17',
        'due_delta' => 2,
        'issue' => 'Customer change request — bulkhead position',
        'issue_short' => 'Customer decision',
        'blocked_category' => 'Customer / Dealer',
        'blocked_reason' => 'Customer requested bulkhead 4" forward of build sheet. Awaiting written sign-off.',
        'time_blocked' => '1d 6h',
        'last_note' => 'Email sent to customer — CS, 4h ago',
        'action' => 'Escalate',
        'parts' => 'Held',
        'parts_risk' => 'med',
        'qc' => '—',
        'bay' => '—',
        'work_center' => 'Engineering',
        'priority' => 'high',
        'notes' => [],
      ],
      [
        'id' => 'S-ORD101388',
        'so' => 'SO-44214',
        'customer' => 'Cascade Electric',
        'dealer' => 'MBPDX',
        'tech' => ['name' => 'Wes Trent', 'initials' => 'WT'],
        'status' => 'in-progress',
        'status_label' => 'In Progress',
        'step' => 'Lighting harness',
        'due' => 'May 14',
        'due_delta' => -1,
        'issue' => 'At risk — scheduled QC slot tight',
        'issue_short' => 'Schedule risk',
        'blocked_category' => null,
        'blocked_reason' => null,
        'time_blocked' => null,
        'last_note' => 'Harness run started — Wes, 18m ago',
        'action' => 'Review schedule',
        'parts' => 'Complete',
        'parts_risk' => 'low',
        'qc' => 'Not started',
        'bay' => 'Bay 3',
        'work_center' => 'Electrical',
        'priority' => 'high',
        'notes' => [],
      ],
      [
        'id' => 'S-ORD101377',
        'so' => 'SO-44203',
        'customer' => 'Roma Trades',
        'dealer' => '—',
        'tech' => ['name' => 'Marco Reyes', 'initials' => 'MR'],
        'status' => 'qc',
        'status_label' => 'In QC',
        'step' => 'Stage 2 QC',
        'due' => 'May 14',
        'due_delta' => -1,
        'issue' => 'Pending stage-2 sign-off',
        'issue_short' => 'Approve closeout',
        'blocked_category' => null,
        'blocked_reason' => null,
        'time_blocked' => null,
        'last_note' => 'Stage 1 QC passed — QC team, 2h ago',
        'action' => 'Review QC',
        'parts' => 'Complete',
        'parts_risk' => 'low',
        'qc' => 'Pending stage 2',
        'bay' => 'QC Bay',
        'work_center' => 'QC',
        'priority' => 'med',
        'notes' => [],
      ],
      [
        'id' => 'S-ORD101372',
        'so' => 'SO-44198',
        'customer' => 'Northland Builders',
        'dealer' => 'MBWIL',
        'tech' => ['name' => 'Devin Park', 'initials' => 'DP'],
        'status' => 'rework',
        'status_label' => 'Rework',
        'step' => 'Cabinetry refit',
        'due' => 'May 15',
        'due_delta' => 0,
        'issue' => 'Drawer slide alignment failed QC',
        'issue_short' => 'Send back to tech',
        'blocked_category' => 'QC Issue',
        'blocked_reason' => 'Drawer slide misalignment — 4 of 6 drawers fail spec.',
        'time_blocked' => '8h',
        'last_note' => 'Rework punch list created — QC team, 1h ago',
        'action' => 'Send back',
        'parts' => 'Complete',
        'parts_risk' => 'low',
        'qc' => 'Failed stage 1',
        'bay' => 'Bay 1',
        'work_center' => 'Cabinetry',
        'priority' => 'high',
        'notes' => [],
      ],
      [
        'id' => 'S-ORD101410',
        'so' => 'SO-44235',
        'customer' => 'Granite State Fleet',
        'dealer' => '—',
        'tech' => null,
        'status' => 'ready',
        'status_label' => 'Ready to Assign',
        'step' => 'Pre-shop kit',
        'due' => 'May 20',
        'due_delta' => 5,
        'issue' => 'Parts kit complete, awaiting assignment',
        'issue_short' => 'Assign tech',
        'blocked_category' => null,
        'blocked_reason' => null,
        'time_blocked' => null,
        'last_note' => 'Kit verified — Parts, today 7:30a',
        'action' => 'Assign tech',
        'parts' => 'Complete',
        'parts_risk' => 'low',
        'qc' => '—',
        'bay' => '—',
        'work_center' => 'Cabinetry',
        'priority' => 'med',
        'notes' => [],
      ],
      [
        'id' => 'S-ORD101411',
        'so' => 'SO-44236',
        'customer' => 'Heartline EMS',
        'dealer' => 'MBPDX',
        'tech' => null,
        'status' => 'ready',
        'status_label' => 'Ready to Schedule',
        'step' => 'Build sheet',
        'due' => 'May 22',
        'due_delta' => 7,
        'issue' => 'Cleared by engineering',
        'issue_short' => 'Schedule into bay',
        'blocked_category' => null,
        'blocked_reason' => null,
        'time_blocked' => null,
        'last_note' => 'Engineering signed off — Logan, today 9:14a',
        'action' => 'Schedule',
        'parts' => 'Partial — 18 of 22 lines',
        'parts_risk' => 'med',
        'qc' => '—',
        'bay' => '—',
        'work_center' => 'Electrical',
        'priority' => 'med',
        'notes' => [],
      ],
      [
        'id' => 'S-ORD101408',
        'so' => 'SO-44233',
        'customer' => 'Coastal Roofing',
        'dealer' => '—',
        'tech' => null,
        'status' => 'hold',
        'status_label' => 'Admin Hold',
        'step' => 'SO verification',
        'due' => 'May 19',
        'due_delta' => 4,
        'issue' => 'Awaiting signed SO copy',
        'issue_short' => 'Waiting on SO',
        'blocked_category' => 'Admin / Paperwork',
        'blocked_reason' => 'SO countersignature not received. CS contacted dealer.',
        'time_blocked' => '5h',
        'last_note' => 'Dealer responded — expect signed copy EOD',
        'action' => 'Follow up',
        'parts' => 'Released to pick',
        'parts_risk' => 'low',
        'qc' => '—',
        'bay' => '—',
        'work_center' => 'Admin',
        'priority' => 'med',
        'notes' => [],
      ],
      [
        'id' => 'S-ORD101376',
        'so' => 'SO-44202',
        'customer' => 'Westport Public Works',
        'dealer' => 'MBWIL',
        'tech' => ['name' => 'Antonia Ruiz', 'initials' => 'AR'],
        'status' => 'blocked',
        'status_label' => 'Blocked',
        'step' => 'Tooling reservation',
        'due' => 'May 15',
        'due_delta' => 0,
        'issue' => 'Bay 5 lift down for service',
        'issue_short' => 'Tooling / bay',
        'blocked_category' => 'Tooling / Bay',
        'blocked_reason' => 'Bay 5 lift offline, maintenance vendor on-site. ETA repair: 2 hours.',
        'time_blocked' => '3h',
        'last_note' => 'Maintenance ETA 11:30a — Facilities',
        'action' => 'Reassign bay',
        'parts' => 'Complete',
        'parts_risk' => 'low',
        'qc' => 'Not started',
        'bay' => 'Bay 5',
        'work_center' => 'Mechanical',
        'priority' => 'high',
        'notes' => [],
      ],
    ];
  }

  public static function get_techs() {
    return [
      ['initials' => 'MR', 'name' => 'Marco Reyes', 'role' => 'Senior Tech', 'current' => ['id' => 'S-ORD101392', 'label' => 'Electrical rough-in'], 'on_job_time' => '2h 14m', 'next' => 'S-ORD101377', 'status' => 'Paused / Blocked', 'needs_help' => true, 'blocker' => 'Parts', 'hours' => '5h 40m'],
      ['initials' => 'DP', 'name' => 'Devin Park', 'role' => 'Tech II', 'current' => ['id' => 'S-ORD101393', 'label' => 'Floor & wall install'], 'on_job_time' => '1h 02m', 'next' => 'S-ORD101372', 'status' => 'Working', 'needs_help' => false, 'blocker' => null, 'hours' => '4h 12m'],
      ['initials' => 'JO', 'name' => 'Jules Okafor', 'role' => 'Tech II', 'current' => ['id' => 'S-ORD101394', 'label' => 'Cabinetry install'], 'on_job_time' => '3h 41m', 'next' => '—', 'status' => 'Working', 'needs_help' => false, 'blocker' => null, 'hours' => '6h 22m'],
      ['initials' => 'AR', 'name' => 'Antonia Ruiz', 'role' => 'Senior Tech', 'current' => ['id' => 'S-ORD101376', 'label' => 'Tooling reservation'], 'on_job_time' => '0h 18m', 'next' => 'S-ORD101350', 'status' => 'Waiting', 'needs_help' => false, 'blocker' => 'Tooling / Bay', 'hours' => '2h 50m'],
      ['initials' => 'WT', 'name' => 'Wes Trent', 'role' => 'Tech III', 'current' => ['id' => 'S-ORD101388', 'label' => 'Lighting harness'], 'on_job_time' => '0h 18m', 'next' => '—', 'status' => 'Working', 'needs_help' => false, 'blocker' => null, 'hours' => '3h 00m'],
      ['initials' => 'SH', 'name' => 'Sam Hadley', 'role' => 'Tech I', 'current' => ['id' => 'S-ORD101401', 'label' => 'Scope review'], 'on_job_time' => '—', 'next' => 'S-ORD101410', 'status' => 'Paused / Blocked', 'needs_help' => false, 'blocker' => 'Customer', 'hours' => '1h 40m'],
      ['initials' => 'KN', 'name' => 'Kira Nakamura', 'role' => 'QC Lead', 'current' => ['id' => 'S-ORD101377', 'label' => 'Stage 2 QC'], 'on_job_time' => '0h 42m', 'next' => 'S-ORD101372', 'status' => 'In QC', 'needs_help' => false, 'blocker' => null, 'hours' => '4h 28m'],
      ['initials' => 'BV', 'name' => 'Beto Valencia', 'role' => 'Tech II', 'current' => null, 'on_job_time' => '—', 'next' => '—', 'status' => 'Needs Assignment', 'needs_help' => false, 'blocker' => null, 'hours' => '0h 00m'],
    ];
  }

  private static function filter_jobs($jobs, $callback) {
    return array_values(array_filter($jobs, $callback));
  }

  public static function get_payload() {
    $jobs = self::get_jobs();
    $techs = self::get_techs();
    $blocked = self::filter_jobs($jobs, function($job) { return !empty($job['blocked_category']); });
    $qc_jobs = self::filter_jobs($jobs, function($job) { return in_array($job['status'], ['qc', 'rework'], true); });
    $ready_jobs = self::filter_jobs($jobs, function($job) { return in_array($job['status'], ['ready', 'complete', 'hold'], true); });
    $at_risk = self::filter_jobs($jobs, function($job) { return (int) $job['due_delta'] <= 0 || $job['parts_risk'] === 'high'; });
    $unassigned = self::filter_jobs($jobs, function($job) { return empty($job['tech']); });

    $payload = [
      'kpis' => [
        ['key' => 'active', 'label' => 'Active Jobs', 'value' => 26, 'sub' => 'Jobs currently open', 'tone' => ''],
        ['key' => 'progress', 'label' => 'In Progress', 'value' => 12, 'sub' => 'Currently being worked', 'tone' => 'sage'],
        ['key' => 'blocked', 'label' => 'Blocked Jobs', 'value' => count($blocked), 'sub' => 'Needs action today', 'tone' => 'blocked'],
        ['key' => 'parts', 'label' => 'Waiting on Parts', 'value' => 3, 'sub' => 'Parts blocking progress', 'tone' => 'arches'],
        ['key' => 'qc', 'label' => 'Pending QC', 'value' => 2, 'sub' => 'Needs supervisor sign-off', 'tone' => 'sage'],
        ['key' => 'rework', 'label' => 'Rework Required', 'value' => 1, 'sub' => 'Returned from QC', 'tone' => 'arches'],
        ['key' => 'due', 'label' => 'Jobs Due This Week', 'value' => 9, 'sub' => 'Inside the 7-day window', 'tone' => ''],
        ['key' => 'risk', 'label' => 'Schedule Risk', 'value' => 5, 'sub' => 'Behind plan or at risk', 'tone' => 'blocked'],
      ],
      'jobs' => $jobs,
      'techs' => $techs,
      'blocked_categories' => self::get_blocked_categories(),
      'schedule' => [
        'cards' => [
          ['label' => 'Scheduled Today', 'value' => 5, 'sub' => 'Jobs with shop time today'],
          ['label' => 'Ready to Schedule', 'value' => 2, 'sub' => 'Cleared for bay planning'],
          ['label' => 'At Risk', 'value' => count($at_risk), 'sub' => 'Due today, past due, or parts risk'],
          ['label' => 'Unassigned', 'value' => count($unassigned), 'sub' => 'Needs tech ownership'],
        ],
        'today' => self::filter_jobs($jobs, function($job) { return !empty($job['tech']) && in_array($job['status'], ['in-progress', 'blocked', 'qc', 'rework'], true); }),
        'at_risk' => $at_risk,
        'ready_to_schedule' => self::filter_jobs($jobs, function($job) { return $job['status'] === 'ready'; }),
        'unassigned' => $unassigned,
        'future' => [
          ['label' => 'Planned Capacity', 'value' => '— hrs / wk', 'sub' => 'Tech hours available next 7 days'],
          ['label' => 'Buffer Usage', 'value' => '— %', 'sub' => 'Slack consumed vs. planned'],
          ['label' => 'Overload Warning', 'value' => '—', 'sub' => 'Flags when scheduled work exceeds capacity'],
          ['label' => 'Bay Load', 'value' => 'Planned', 'sub' => 'Bay-level utilization preview'],
          ['label' => 'Work Center Load', 'value' => 'Planned', 'sub' => 'Electrical, interior, cabinetry, QC'],
        ],
      ],
      'qc' => [
        'pending' => self::filter_jobs($jobs, function($job) { return $job['status'] === 'qc'; }),
        'failed' => self::filter_jobs($jobs, function($job) { return $job['qc'] === 'Failed stage 1'; }),
        'rework' => self::filter_jobs($jobs, function($job) { return $job['status'] === 'rework'; }),
        'signoff' => self::filter_jobs($jobs, function($job) { return $job['status'] === 'complete'; }),
      ],
      'ready_queue' => [
        'assign' => self::filter_jobs($jobs, function($job) { return $job['status'] === 'ready' && $job['action'] === 'Assign tech'; }),
        'schedule' => self::filter_jobs($jobs, function($job) { return $job['status'] === 'ready' && $job['action'] === 'Schedule'; }),
        'partial_schedulable' => self::filter_jobs($jobs, function($job) { return $job['parts_risk'] === 'med' && in_array($job['status'], ['ready', 'in-progress'], true); }),
        'admin_hold' => self::filter_jobs($jobs, function($job) { return $job['status'] === 'hold'; }),
      ],
      'attention' => [
        ['label' => 'Oldest blocked job', 'value' => 'S-ORD101392', 'detail' => 'Parts blocker open 2d 4h'],
        ['label' => 'Tech needing help', 'value' => 'Marco Reyes', 'detail' => 'Paused on wiring harness'],
        ['label' => 'Job due soon', 'value' => 'S-ORD101388', 'detail' => 'QC slot tight today'],
        ['label' => 'QC item waiting', 'value' => 'S-ORD101377', 'detail' => 'Stage 2 sign-off pending'],
        ['label' => 'Parts risk item', 'value' => 'S-ORD101411', 'detail' => 'Partial parts but schedulable'],
      ],
      'tabs' => self::get_tabs(),
    ];

    return apply_filters('slate_ops_supervisor_refresh', $payload);
  }
}
