/* Sample data for the Slate Ops Supervisor Dashboard prototype.
   Names are fictional; SO numbers follow the S-ORD prefix used in the CS dashboard. */

const JOBS = [
  {
    id: "S-ORD101392",
    so: "SO-44218",
    customer: "Sigma Logistics",
    dealer: "MBWIL",
    tech: { name: "Marco Reyes", initials: "MR" },
    status: "blocked",
    statusLabel: "Blocked",
    step: "Electrical rough-in",
    due: "May 14",
    dueDelta: -1,
    issue: "Awaiting wiring harness — vendor revised ETA",
    issueShort: "Parts hold",
    blockedCategory: "Parts",
    blockedReason: "Wiring harness PN 44-218B back-ordered. Vendor revised ETA to 5/16.",
    timeBlocked: "2d 4h",
    lastNote: "Vendor confirmed 5/16 ship — Logan, 1h ago",
    action: "Review blocker",
    parts: "Partial — 6 of 8 lines",
    partsRisk: "high",
    qc: "Not started",
    bay: "Bay 4",
    workCenter: "Electrical",
    priority: "high",
    notes: [
      { who: "Logan T.", role: "Parts", when: "1h ago", text: "Vendor confirmed 5/16 ship. PO updated." },
      { who: "Marco R.", role: "Tech",  when: "Yesterday 4:12p", text: "Harness short — cannot continue trim. Moving to next available task." },
      { who: "Supervisor", role: "Sup", when: "Yesterday 9:08a", text: "Hold posted. Helper not required." }
    ]
  },
  {
    id: "S-ORD101393",
    so: "SO-44219",
    customer: "Sigma Logistics",
    dealer: "MBWIL",
    tech: { name: "Devin Park", initials: "DP" },
    status: "in-progress",
    statusLabel: "In Progress",
    step: "Floor & wall install",
    due: "May 15",
    dueDelta: 0,
    issue: "On track — confirm parts ETA for ladder rack",
    issueShort: "Confirm parts ETA",
    blockedCategory: null,
    timeBlocked: null,
    lastNote: "Floor primer complete — Devin, 22m ago",
    action: "Confirm ETA",
    parts: "Complete",
    partsRisk: "low",
    qc: "Pending stage 2",
    bay: "Bay 2",
    workCenter: "Interior",
    priority: "med",
    notes: []
  },
  {
    id: "S-ORD101394",
    so: "SO-44220",
    customer: "Sigma Logistics",
    dealer: "MBWIL",
    tech: { name: "Jules Okafor", initials: "JO" },
    status: "in-progress",
    statusLabel: "In Progress",
    step: "Cabinetry install",
    due: "May 16",
    dueDelta: 1,
    issue: "Decision needed: customer-supplied shelving variant",
    issueShort: "Decision needed",
    blockedCategory: null,
    timeBlocked: null,
    lastNote: "Cabinet template fit-checked — Jules, 1h ago",
    action: "Resolve parts hold",
    parts: "Partial — 12 of 14 lines",
    partsRisk: "med",
    qc: "Not started",
    bay: "Bay 1",
    workCenter: "Cabinetry",
    priority: "med",
    notes: []
  },
  {
    id: "S-ORD101350",
    so: "SO-44181",
    customer: "Mercedes-Benz of Wilsonville",
    dealer: "MBWIL",
    tech: { name: "Antonia Ruiz", initials: "AR" },
    status: "complete",
    statusLabel: "Complete — Awaiting Pickup",
    step: "Closeout",
    due: "May 13",
    dueDelta: 0,
    issue: "Ready for pickup notification",
    issueShort: "Notify customer",
    blockedCategory: null,
    timeBlocked: null,
    lastNote: "Closeout photos uploaded — Antonia, 3h ago",
    action: "Notify customer",
    parts: "Complete",
    partsRisk: "low",
    qc: "Signed off",
    bay: "Bay 6",
    workCenter: "Closeout",
    priority: "low",
    notes: []
  },
  {
    id: "S-ORD101401",
    so: "SO-44226",
    customer: "Pacific Plumbing Co.",
    dealer: "—",
    tech: { name: "Sam Hadley", initials: "SH" },
    status: "blocked",
    statusLabel: "Blocked",
    step: "Scope review",
    due: "May 17",
    dueDelta: 2,
    issue: "Customer change request — bulkhead position",
    issueShort: "Customer decision",
    blockedCategory: "Customer / Dealer",
    blockedReason: "Customer requested bulkhead 4\" forward of build sheet. Awaiting written sign-off.",
    timeBlocked: "1d 6h",
    lastNote: "Email sent to customer — CS, 4h ago",
    action: "Escalate",
    parts: "Held",
    partsRisk: "med",
    qc: "—",
    bay: "—",
    workCenter: "Engineering",
    priority: "high",
    notes: []
  },
  {
    id: "S-ORD101388",
    so: "SO-44214",
    customer: "Cascade Electric",
    dealer: "MBPDX",
    tech: { name: "Wes Trent", initials: "WT" },
    status: "in-progress",
    statusLabel: "In Progress",
    step: "Lighting harness",
    due: "May 14",
    dueDelta: -1,
    issue: "At risk — scheduled QC slot tight",
    issueShort: "Schedule risk",
    blockedCategory: null,
    timeBlocked: null,
    lastNote: "Harness run started — Wes, 18m ago",
    action: "Review schedule",
    parts: "Complete",
    partsRisk: "low",
    qc: "Not started",
    bay: "Bay 3",
    workCenter: "Electrical",
    priority: "high",
    notes: []
  },
  {
    id: "S-ORD101377",
    so: "SO-44203",
    customer: "Roma Trades",
    dealer: "—",
    tech: { name: "Marco Reyes", initials: "MR" },
    status: "qc",
    statusLabel: "In QC",
    step: "Stage 2 QC",
    due: "May 14",
    dueDelta: -1,
    issue: "Pending stage-2 sign-off",
    issueShort: "Approve closeout",
    blockedCategory: null,
    timeBlocked: null,
    lastNote: "Stage 1 QC passed — QC team, 2h ago",
    action: "Review QC",
    parts: "Complete",
    partsRisk: "low",
    qc: "Pending stage 2",
    bay: "QC Bay",
    workCenter: "QC",
    priority: "med",
    notes: []
  },
  {
    id: "S-ORD101372",
    so: "SO-44198",
    customer: "Northland Builders",
    dealer: "MBWIL",
    tech: { name: "Devin Park", initials: "DP" },
    status: "rework",
    statusLabel: "Rework",
    step: "Cabinetry refit",
    due: "May 15",
    dueDelta: 0,
    issue: "Drawer slide alignment failed QC",
    issueShort: "Send back to tech",
    blockedCategory: "QC Issue",
    blockedReason: "Drawer slide misalignment — 4 of 6 drawers fail spec.",
    timeBlocked: "8h",
    lastNote: "Rework punch list created — QC team, 1h ago",
    action: "Send back",
    parts: "Complete",
    partsRisk: "low",
    qc: "Failed stage 1",
    bay: "Bay 1",
    workCenter: "Cabinetry",
    priority: "high",
    notes: []
  },
  {
    id: "S-ORD101410",
    so: "SO-44235",
    customer: "Granite State Fleet",
    dealer: "—",
    tech: null,
    status: "ready",
    statusLabel: "Ready to Assign",
    step: "Pre-shop kit",
    due: "May 20",
    dueDelta: 5,
    issue: "Parts kit complete, awaiting assignment",
    issueShort: "Assign tech",
    blockedCategory: null,
    timeBlocked: null,
    lastNote: "Kit verified — Parts, today 7:30a",
    action: "Assign tech",
    parts: "Complete",
    partsRisk: "low",
    qc: "—",
    bay: "—",
    workCenter: "Cabinetry",
    priority: "med",
    notes: []
  },
  {
    id: "S-ORD101411",
    so: "SO-44236",
    customer: "Heartline EMS",
    dealer: "MBPDX",
    tech: null,
    status: "ready",
    statusLabel: "Ready to Schedule",
    step: "Build sheet",
    due: "May 22",
    dueDelta: 7,
    issue: "Cleared by engineering",
    issueShort: "Schedule into bay",
    blockedCategory: null,
    timeBlocked: null,
    lastNote: "Engineering signed off — Logan, today 9:14a",
    action: "Schedule",
    parts: "Partial — 18 of 22 lines",
    partsRisk: "med",
    qc: "—",
    bay: "—",
    workCenter: "Electrical",
    priority: "med",
    notes: []
  },
  {
    id: "S-ORD101408",
    so: "SO-44233",
    customer: "Coastal Roofing",
    dealer: "—",
    tech: null,
    status: "hold",
    statusLabel: "Admin Hold",
    step: "SO verification",
    due: "May 19",
    dueDelta: 4,
    issue: "Awaiting signed SO copy",
    issueShort: "Waiting on SO",
    blockedCategory: "Admin / Paperwork",
    blockedReason: "SO countersignature not received. CS contacted dealer.",
    timeBlocked: "5h",
    lastNote: "Dealer responded — expect signed copy EOD",
    action: "Follow up",
    parts: "Released to pick",
    partsRisk: "low",
    qc: "—",
    bay: "—",
    workCenter: "Admin",
    priority: "med",
    notes: []
  },
  {
    id: "S-ORD101376",
    so: "SO-44202",
    customer: "Westport Public Works",
    dealer: "MBWIL",
    tech: { name: "Antonia Ruiz", initials: "AR" },
    status: "blocked",
    statusLabel: "Blocked",
    step: "Tooling reservation",
    due: "May 15",
    dueDelta: 0,
    issue: "Bay 5 lift down for service",
    issueShort: "Tooling / bay",
    blockedCategory: "Tooling / Bay",
    blockedReason: "Bay 5 lift offline, maintenance vendor on-site. ETA repair: 2 hours.",
    timeBlocked: "3h",
    lastNote: "Maintenance ETA 11:30a — Facilities",
    action: "Reassign bay",
    parts: "Complete",
    partsRisk: "low",
    qc: "Not started",
    bay: "Bay 5",
    workCenter: "Mechanical",
    priority: "high",
    notes: []
  }
];

const TECHS = [
  {
    initials: "MR", name: "Marco Reyes", role: "Senior Tech",
    current: { id: "S-ORD101392", label: "Electrical rough-in" },
    onJobTime: "2h 14m",
    next: "S-ORD101377",
    status: "Paused / Blocked",
    needsHelp: true,
    blocker: "Parts",
    hours: "5h 40m"
  },
  {
    initials: "DP", name: "Devin Park", role: "Tech II",
    current: { id: "S-ORD101393", label: "Floor & wall install" },
    onJobTime: "1h 02m",
    next: "S-ORD101372",
    status: "Working",
    needsHelp: false,
    blocker: null,
    hours: "4h 12m"
  },
  {
    initials: "JO", name: "Jules Okafor", role: "Tech II",
    current: { id: "S-ORD101394", label: "Cabinetry install" },
    onJobTime: "3h 41m",
    next: "—",
    status: "Working",
    needsHelp: false,
    blocker: null,
    hours: "6h 22m"
  },
  {
    initials: "AR", name: "Antonia Ruiz", role: "Senior Tech",
    current: { id: "S-ORD101376", label: "Tooling reservation" },
    onJobTime: "0h 18m",
    next: "S-ORD101350",
    status: "Waiting",
    needsHelp: false,
    blocker: "Tooling / Bay",
    hours: "2h 50m"
  },
  {
    initials: "WT", name: "Wes Trent", role: "Tech III",
    current: { id: "S-ORD101388", label: "Lighting harness" },
    onJobTime: "0h 18m",
    next: "—",
    status: "Working",
    needsHelp: false,
    blocker: null,
    hours: "3h 00m"
  },
  {
    initials: "SH", name: "Sam Hadley", role: "Tech I",
    current: { id: "S-ORD101401", label: "Scope review" },
    onJobTime: "—",
    next: "S-ORD101410",
    status: "Paused / Blocked",
    needsHelp: false,
    blocker: "Customer",
    hours: "1h 40m"
  },
  {
    initials: "KN", name: "Kira Nakamura", role: "QC Lead",
    current: { id: "S-ORD101377", label: "Stage 2 QC" },
    onJobTime: "0h 42m",
    next: "S-ORD101372",
    status: "In QC",
    needsHelp: false,
    blocker: null,
    hours: "4h 28m"
  },
  {
    initials: "BV", name: "Beto Valencia", role: "Tech II",
    current: null,
    onJobTime: "—",
    next: "—",
    status: "Needs Assignment",
    needsHelp: false,
    blocker: null,
    hours: "0h 00m"
  }
];

const TAB_DEFS = [
  { id: "overview", label: "Overview" },
  { id: "blocked",  label: "Blocked Jobs", countKey: "blocked" },
  { id: "schedule", label: "Schedule" },
  { id: "techs",    label: "Techs" },
  { id: "qc",       label: "QC / Rework", countKey: "qc" },
  { id: "ready",    label: "Ready Queue", countKey: "ready" }
];

const BLOCKED_CATEGORIES = [
  "Parts",
  "Scope / Engineering",
  "Customer / Dealer",
  "QC Issue",
  "Tooling / Bay",
  "Tech Needs Help",
  "Admin / Paperwork"
];

const KPIS = [
  { key: "active",   label: "Active Jobs",         value: 26, sub: "Jobs currently open" },
  { key: "progress", label: "In Progress",         value: 12, sub: "Currently being worked",       dot: "ok" },
  { key: "blocked",  label: "Blocked Jobs",        value: 4,  sub: "Needs action today",           dot: "warn", emphasis: true },
  { key: "parts",    label: "Waiting on Parts",    value: 3,  sub: "Parts blocking progress",      dot: "warn" },
  { key: "qc",       label: "Pending QC",          value: 2,  sub: "Needs supervisor sign-off",    dot: "ok" },
  { key: "rework",   label: "Rework Required",     value: 1,  sub: "Returned from QC",             dot: "warn" },
  { key: "due",      label: "Jobs Due This Week",  value: 9,  sub: "Inside the 7-day window" },
  { key: "risk",     label: "Schedule Risk",       value: 5,  sub: "Behind plan or at risk",       dot: "danger" }
];

Object.assign(window, {
  JOBS, TECHS, TAB_DEFS, BLOCKED_CATEGORIES, KPIS
});
